const { google } = require('googleapis');
const config = require('../config');
const gemini = require('../lib/gemini');
const mistral = require('../lib/mistral');
const drive = require('../lib/drive');
const pdf = require('../lib/pdf');
const slack = require('../lib/slack');
const logger = require('../utils/logger');

const auth = new google.auth.GoogleAuth({
  keyFile: './google-credentials.json',
  scopes: ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive'],
});

let aiConfig = {
    emailColumns: ['Current Status', 'Task and Status comments', 'Template'],
    slackColumns: ['Current Status', 'Task and Status comments', 'Template']
};

function extractLatestNotes(text) {
    if (!text) return "";
    const sections = text.split(/\n\s*\n/);
    return sections[0].trim();
}

async function getVisibleHeaders(gsapi, spreadsheetId, sheetName) {
    const spreadsheet = await gsapi.spreadsheets.get({
        spreadsheetId,
        includeGridData: true,
        ranges: [`${sheetName}!1:1`]
    });
    const sheet = spreadsheet.data.sheets.find(s => s.properties.title === sheetName);
    if (!sheet || sheet.properties.hidden) return null;
    const columnsMetadata = sheet.data[0].columnMetadata || [];
    const rowData = sheet.data[0].rowData[0].values || [];
    return rowData.map((cell, index) => {
        const isHidden = columnsMetadata[index] && (columnsMetadata[index].hiddenByFilter || columnsMetadata[index].pixelSize === 0);
        return isHidden ? null : (cell.formattedValue ? cell.formattedValue.trim() : null);
    });
}

async function runAutomationTask(task) {
    const { sheetName, rowIndex, triggerValue } = task;
    let authClient, gsapi, projectName = 'System';
    const sid = `task-${Date.now()}`;

    try {
        logger.log(`Connecting to Workspace...`, 'loading', 'System', `${sid}-auth`);
        authClient = await auth.getClient();
        gsapi = google.sheets({ version: 'v4', auth: authClient });
        logger.log(`Connected to Google APIs.`, 'success', 'System', `${sid}-auth`);

        logger.log(`Fetching project data...`, 'loading', sheetName, `${sid}-data`);
        const headers = await getVisibleHeaders(gsapi, config.SPREADSHEET_ID, sheetName);
        if (!headers) throw new Error("Sheet is hidden.");

        const response = await gsapi.spreadsheets.values.get({
            spreadsheetId: config.SPREADSHEET_ID,
            range: `${sheetName}!A${rowIndex}:AN${rowIndex}`,
        });
        const rowData = response.data.values ? response.data.values[0] : null;
        if (!rowData) throw new Error("Row is empty.");
        
        projectName = rowData[headers.indexOf('Project Name')] || rowData[1] || 'Unknown';
        const dateSuffix = new Date().toLocaleDateString('en-GB').replace(/\//g, '-');
        logger.log(`Data locked for ${projectName}.`, 'success', projectName, `${sid}-data`);

        if (triggerValue.toLowerCase() === 'new') {
            logger.log(`Compiling AI Context...`, 'loading', projectName, `${sid}-ctx`);
            const buildCtx = (cols) => {
                const ctx = {};
                cols.forEach(c => {
                    const i = headers.indexOf(c);
                    if (i !== -1 && rowData[i]) {
                        let val = rowData[i].trim();
                        if (c === 'Task and Status comments') val = extractLatestNotes(val);
                        if (val && val !== "-") ctx[c] = val;
                    }
                });
                return ctx;
            };
            const context = { email: buildCtx(aiConfig.emailColumns), slack: buildCtx(aiConfig.slackColumns) };
            logger.log(`Context ready.`, 'success', projectName, `${sid}-ctx`);

            // AI PROCESS WITH WARNING FAILOVER
            logger.log(`AI Synthesis (Gemini 2.5 Flash)...`, 'loading', projectName, `${sid}-ai`);
            let drafts;
            try {
                drafts = await gemini.generateAIDrafts(projectName, context);
                logger.log(`Drafts generated by Gemini.`, 'success', projectName, `${sid}-ai`);
            } catch (err) {
                // THE FIX: Send a warning log instead of keeping the loading spinner
                logger.log(`Gemini Limit hit. Failing over to Mistral...`, 'warning', projectName, `${sid}-ai`);
                
                // Pause for a moment so the user can actually see the warning in the UI
                await new Promise(r => setTimeout(r, 1500)); 
                
                // Now proceed with Mistral
                drafts = await mistral.generateAIDrafts(projectName, context);
                logger.log(`Drafts generated by Mistral (Failover).`, 'success', projectName, `${sid}-ai`);
            }

            logger.log(`Generating Documents...`, 'loading', projectName, `${sid}-docs`);
            const html = `<html>${config.EMAIL_CSS_SKELETON}<body>${drafts.email}</body></html>`;
            const pdfBuf = await pdf.convertHTMLToPDF(html);
            const emailLink = await drive.uploadPDFToDrive(authClient, `emailWSR-${projectName}-${dateSuffix}.pdf`, pdfBuf);
            const slackLink = await drive.createSlackDoc(authClient, `slackWSR-${projectName}-${dateSuffix}`, drafts.slack);
            logger.log(`Documents published to Drive.`, 'success', projectName, `${sid}-docs`);

            logger.log(`Updating Sheet...`, 'loading', projectName, `${sid}-wb`);
            await gsapi.spreadsheets.values.update({
                spreadsheetId: config.SPREADSHEET_ID,
                range: `${sheetName}!AJ${rowIndex}:AK${rowIndex}`,
                valueInputOption: 'RAW',
                resource: { values: [[ String(drafts.slack), String(slackLink), String(emailLink), 'under review' ]] }
            });
            logger.log(`✅ Generation Complete.`, 'success', projectName, `${sid}-wb`);
        }
        else if (triggerValue.toLowerCase() === 'approved') {
            logger.log(`Distributing to Slack...`, 'loading', projectName, `${sid}-slack`);
            const slackChannelId = rowData[headers.indexOf('Slack Channel ID')] || rowData[34]; 
            const slackMessage = rowData[headers.indexOf('Slack Draft (Raw Text)')] || rowData[35];

            if (!slackChannelId || !slackMessage) throw new Error("Missing Slack details.");

            const isSuccess = await slack.sendSlackUpdate(slackChannelId, slackMessage);
            if (isSuccess) {
                await gsapi.spreadsheets.values.update({
                    spreadsheetId: config.SPREADSHEET_ID,
                    range: `${sheetName}!AM${rowIndex}`,
                    valueInputOption: 'RAW',
                    resource: { values: [['published']] }
                });
                logger.log(`🚀 Distribution Complete.`, 'success', projectName, `${sid}-slack`);
            } else {
                throw new Error("Slack API Error.");
            }
        }
    } catch (e) {
        logger.log(`Error: ${e.message}`, 'error', projectName, sid);
    }
}

async function getVisibleHeadersForUi() {
    const authClient = await auth.getClient();
    const gsapi = google.sheets({ version: 'v4', auth: authClient });
    const meta = await gsapi.spreadsheets.get({ spreadsheetId: config.SPREADSHEET_ID });
    const firstSheet = meta.data.sheets.find(s => !s.properties.hidden);
    const headers = await getVisibleHeaders(gsapi, config.SPREADSHEET_ID, firstSheet.properties.title);
    return { headers: headers.filter(h => h !== null), activeConfig: aiConfig };
}

function updateAiConfig(newConfig) {
    if (newConfig.emailColumns) aiConfig.emailColumns = newConfig.emailColumns;
    if (newConfig.slackColumns) aiConfig.slackColumns = newConfig.slackColumns;
}

module.exports = { runAutomationTask, getVisibleHeadersForUi, updateAiConfig };